{"time":"2025-03-17T22:39:06.9420236+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_223906-s390guc8\\logs\\debug-core.log"}
{"time":"2025-03-17T22:39:07.0567173+05:30","level":"INFO","msg":"created new stream","id":"s390guc8"}
{"time":"2025-03-17T22:39:07.0567173+05:30","level":"INFO","msg":"stream: started","id":"s390guc8"}
{"time":"2025-03-17T22:39:07.0567173+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"s390guc8"}
{"time":"2025-03-17T22:39:07.0567173+05:30","level":"INFO","msg":"sender: started","stream_id":"s390guc8"}
{"time":"2025-03-17T22:39:07.0567173+05:30","level":"INFO","msg":"handler: started","stream_id":"s390guc8"}
{"time":"2025-03-17T22:39:07.462089+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T22:39:22.786468+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T22:39:22.7875378+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T22:39:23.7949917+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-4, summary","runtime_seconds":0.5609293},{"desc":"uploading config.yaml","runtime_seconds":0.0659043,"progress":"1002B/1002B"}],"total_operations":2}}
{"time":"2025-03-17T22:39:24.0952502+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T22:39:44.2863095+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:40:07.4528927+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:40:24.0154122+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-4, summary","runtime_seconds":60.7813498,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:40:33.1512025+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:41:02.5586591+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:41:24.1470977+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":42.6329372,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:41:26.0563076+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:41:51.4860223+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:42:21.8543802+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:42:24.2469233+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":102.7327628,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:43:00.021719+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:43:24.4906376+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":162.9764771,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:44:00.5563643+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:44:24.7939077+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":223.2797472,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/s390guc8/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:45:00.8932641+05:30","level":"INFO","msg":"stream: closing","id":"s390guc8"}
{"time":"2025-03-17T22:45:00.8932641+05:30","level":"INFO","msg":"handler: closed","stream_id":"s390guc8"}
{"time":"2025-03-17T22:45:00.8932641+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"s390guc8"}
{"time":"2025-03-17T22:45:00.8932641+05:30","level":"INFO","msg":"sender: closed","stream_id":"s390guc8"}
{"time":"2025-03-17T22:45:00.8938862+05:30","level":"INFO","msg":"stream: closed","id":"s390guc8"}
